Day=int(input())
if(Day==1):
    print("Monday")
elif(Day==2):
    print("Tueaday")
elif(Day==3):
    print("Wednesday")
elif(Day==4):
    print("Thursday")
elif(Day==5):
    print("Friday")
elif(Day==6):
    print("Saturday")
else:
    print("Sunday")